name: "Publish Service Documentation"
description: "Publishes services documentation to swagger.extrahorizon.com"
inputs:
  ref:
    description: "Ref of repo"
    required: false
    default: ${{github.ref}}

runs:
  using: composite
  steps:
    - name: Configure documentation version
      run: |
        if [ "${{inputs.ref}}" == "refs/heads/master" ]
        then
          documentation_version=${PROJECT_VERSION}
        else
          documentation_version="${PROJECT_VERSION}-dev"
        fi

        documentation_path="services/${PROJECT_NAME}/$documentation_version"
        echo "DOCUMENTATION_PATH=$documentation_path" >> $GITHUB_ENV
      shell: bash

    - name: Publish the Documentation to AWS
      run: |
        aws s3 sync --acl public-read --delete ./documentation/developers/ s3://swagger.extrahorizon.com/${DOCUMENTATION_PATH}
        aws cloudfront create-invalidation --distribution-id E7MY46MSBV6S4 --paths /${DOCUMENTATION_PATH}/*
      shell: bash
